[[houses]]
name = "80/10/10 30 year 2020 Cheap"
price = 900000
[houses.mortgage]
rate = 0.031
term = 30
down = 0.1
[[houses]]
name = "20% down 2021 Medium"
price = 1000000
[houses.mortgage]
rate = 0.0315
term = 30
down = 0.2
